# Generated by Django 3.0.4 on 2020-11-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cciit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('start_work', models.CharField(max_length=10, verbose_name='время начала работы')),
                ('end_work', models.CharField(max_length=10, verbose_name='время окончания работы')),
                ('photo', models.ImageField(null=True, upload_to='engineer')),
            ],
            options={
                'verbose_name': 'Инженеры',
                'verbose_name_plural': 'Инженеры',
            },
        ),
    ]
