# Generated by Django 3.0.4 on 2020-11-24 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cciit', '0004_cabinet_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Кабинет')),
                ('Cabinet_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cciit.Cabinet_name', verbose_name='Название кабинета')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинет',
            },
        ),
    ]
