# Generated by Django 3.0.4 on 2020-11-24 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cciit', '0005_cabinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineers',
            name='Cabinet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cciit.Cabinet', verbose_name=''),
        ),
    ]
