# Generated by Django 3.0.4 on 2020-11-24 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cciit', '0006_engineers_cabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineers',
            name='Cabinet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cciit.Cabinet', verbose_name='Кабинет'),
        ),
        migrations.CreateModel(
            name='Available_techniques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KODTMU', models.IntegerField(default=11111111, verbose_name='КодТМУ')),
                ('Names', models.CharField(max_length=255, null=True, verbose_name='Наименования')),
                ('Quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('sostoyani', models.CharField(choices=[('рабочий', 'рабочий'), ('не рабочий', 'не рабочий')], max_length=20, null=True, verbose_name='Состояние')),
                ('Cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cciit.Cabinet', verbose_name='Кабинет')),
                ('Cabinet_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cciit.Cabinet_name', verbose_name='Тип Кабинета')),
                ('Categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cciit.Categories', verbose_name='Категории')),
                ('Unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cciit.Unit', verbose_name='Ед.изм.')),
            ],
            options={
                'verbose_name': 'Наличие техники',
                'verbose_name_plural': 'Наличие техники',
            },
        ),
    ]
