# Generated by Django 3.0.4 on 2020-11-24 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naimenovanie', models.CharField(max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Edizm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naimenovanie', models.CharField(max_length=50, verbose_name='ЕдИзм')),
            ],
            options={
                'verbose_name': 'ЕдИзм',
                'verbose_name_plural': 'ЕдИзм',
            },
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aty', models.CharField(max_length=50, verbose_name='ФИО')),
                ('doljnosti', models.CharField(max_length=100, verbose_name='Должность')),
                ('tel', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('start_work', models.CharField(max_length=10, verbose_name='время начала работы')),
                ('end_work', models.CharField(max_length=10, verbose_name='время окончания работы')),
                ('photo', models.ImageField(null=True, upload_to='engineer')),
            ],
            options={
                'verbose_name': 'Инженеры и лаборанты',
                'verbose_name_plural': 'Инженеры и лаборанты',
            },
        ),
        migrations.CreateModel(
            name='Ingener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aty', models.CharField(max_length=40, verbose_name='ФИО')),
                ('tel', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('photo', models.ImageField(null=True, upload_to='фото')),
            ],
            options={
                'verbose_name': 'Программист',
                'verbose_name_plural': 'Программист',
            },
        ),
        migrations.CreateModel(
            name='Kabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naimenovanie', models.CharField(max_length=50, verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинет',
            },
        ),
        migrations.CreateModel(
            name='NamKabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naimenovanie', models.CharField(max_length=100, verbose_name='Название кабинета')),
            ],
            options={
                'verbose_name': 'Название кабинета',
                'verbose_name_plural': 'Название кабинета',
            },
        ),
        migrations.CreateModel(
            name='NalichiTehniki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodTMU', models.IntegerField(default=11111111, verbose_name='КодТМУ')),
                ('Naimenovanie', models.CharField(max_length=255, null=True, verbose_name='Наименования')),
                ('Kolich', models.IntegerField(default=1, verbose_name='Количество')),
                ('sostoyanie', models.CharField(choices=[('рабочий', 'рабочий'), ('не рабочий', 'не рабочий')], max_length=20, null=True, verbose_name='Состояние')),
                ('Edizm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.Edizm', verbose_name='Ед.изм.')),
                ('Kabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Kabinet', verbose_name='Кабинет')),
                ('NamKabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.NamKabinet', verbose_name='Тип Кабинета')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Наличие техники',
                'verbose_name_plural': 'Наличие техники',
            },
        ),
        migrations.CreateModel(
            name='Mebel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aty', models.CharField(max_length=100, verbose_name='Аты')),
                ('kodTMU', models.IntegerField(verbose_name='КодТМУ')),
                ('kolich', models.IntegerField(verbose_name='Количество')),
                ('Edizm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Edizm', verbose_name='Ед.изм.')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Engineer', verbose_name='Инженер')),
                ('kabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Kabinet', verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Мебель',
                'verbose_name_plural': 'Мебель',
            },
        ),
        migrations.AddField(
            model_name='kabinet',
            name='NamKabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.NamKabinet', verbose_name='Название кабинета'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='kabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Kabinet', verbose_name='Кабинет'),
        ),
    ]
