# Generated by Django 3.0.4 on 2021-01-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='book',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
