# Generated by Django 3.0.4 on 2020-05-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_engineer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/engineer'),
        ),
    ]
