# Generated by Django 3.0.4 on 2021-01-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_documents_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'Название кабинета', 'verbose_name_plural': 'Название кабинета'},
        ),
        migrations.AddField(
            model_name='documents',
            name='file',
            field=models.FilePathField(default=2),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='documents',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='documents',
            name='book',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='name',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='year',
        ),
    ]
