# Generated by Django 3.0.4 on 2021-01-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20210127_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(upload_to='Документы', verbose_name='Документы'),
        ),
    ]
