# Generated by Django 3.0.4 on 2021-01-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20210127_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(null=True, upload_to='Документы'),
        ),
    ]
