# Generated by Django 3.0.4 on 2021-01-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20210127_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(blank=True, default=2, upload_to='Документы'),
            preserve_default=False,
        ),
    ]
