# Generated by Django 3.0.4 on 2021-01-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_documents_atyy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='file',
            new_name='fil',
        ),
    ]
