# Generated by Django 3.0.4 on 2021-01-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_auto_20210127_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='fil',
            new_name='document',
        ),
    ]
