# Generated by Django 3.0.4 on 2021-01-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_auto_20210127_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(max_length=60, upload_to='Документы'),
        ),
    ]
