# Generated by Django 3.0.4 on 2021-01-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_auto_20210127_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
