# Generated by Django 3.0.4 on 2021-02-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0004_auto_20210202_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(max_length=60, upload_to='document/', verbose_name='Файл'),
        ),
    ]
